# Generated by Django 2.0.1 on 2018-01-20 05:53

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_thumb',
            field=sorl.thumbnail.fields.ImageField(upload_to='media/thumbs'),
        ),
    ]
