# Generated by Django 2.0.1 on 2018-01-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180120_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_thumb',
            field=models.ImageField(upload_to='media/thumbs/'),
        ),
    ]
