# Generated by Django 2.0.1 on 2018-01-28 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180120_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('is_user', models.BooleanField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Photo')),
            ],
        ),
    ]
