# Generated by Django 2.0.1 on 2018-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='face_encodings',
            field=models.BinaryField(null=True),
        ),
    ]
